name: Generate Social Video

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a specific version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or specify a specific version like '3.11'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          uv add moviepy click soundfile kokoro faster_whisper pytube pytubefix en-core-web-sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
          sudo apt-get -qq -y install espeak-ng
          sudo apt-get -y install python3-pip

      - name: Set up Filesystem
        run: |
          mkdir -p media media/audios media/videos media/outputs media/scripts .secrets

      - name: Setup Playwright
        run: |
          bunx playwright install chromium

      - name: Download YouTube video
        run: |
          bun download.ts

      - name: Set up Environment Variables
        run: |
          echo "${{ secrets.ENV_FILE }}" >> .env
          echo "${{ secrets.SECRETS_FILE }}" >> .secrets/google_client_secret.json

      - name: Run video generation script
        run: |
          source .venv/bin/activate
          bun src/index.ts generate --limit 3 --concurrent 1 --platform youtube --skip-upload

      - name: Upload output videos
        uses: actions/upload-artifact@v4
        with:
          name: generated-videos
          path: media/outputs/**/*.mp4

      - name: Run video generation script
        run: |
          source .venv/bin/activate
          bun src/index.ts upload --platform youtube --story all
