name: Generate Social Video

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a specific version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Or specify a specific version like '3.11'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          uv add moviepy click soundfile kokoro faster_whisper pytube pytubefix
          apt-get -qq -y install espeak-ng

      - name: Set up Filesystem
        run: |
          mkdir -p media
          mkdir -p media/audio
          mkdir -p media/video
          mkdir -p media/outputs
          mkdir -p media/scripts
      
      - name: Setup Playwright
        run: |
          bunx playwright install chromium

      - name: Download YouTube video
        run: |
          bun download.ts

      - name: Set up Environment Variables
        run: |
          echo "${{ secrets.ENV_FILE }}" >> .env

      - name: Run video generation script
        # Generates 1 video using the filesystem uploader
        # Add secrets and adjust platform/options if uploading to external services
        run: |
          source .venv/bin/activate
          bun src/index.ts generate --limit 3 --concurrent 1 --platform youtube
